In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
import pandas as pd
import numpy as np
import shutil
import scipy.stats as stats
import statsmodels.api as sm
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.utils import resample
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from statsmodels.stats.diagnostic import het_breuschpagan
from tabulate import tabulate
from openpyxl import load_workbook
import os

c:\Users\thgcn\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject

In [24]:
path = r'C:\Users\thgcn\OneDrive\Academico\Financial-Reports-Impact\analise_sentimento'
relatorio = pd.read_csv(f"{path}/relatorio.csv", sep=(','))
transcricao = pd.read_csv(f"{path}/transcricao.csv")

In [20]:
relatorio.columns = ["index", "subdirectory_filename", "data_formatada", "Posi", "pos_ind", "Neg", "neg_ind", "Neutral", "neu_ind", "indice"]

In [21]:
relatorio.to_csv(f"{path}/relatorio.csv", index=False)

In [31]:
rel=relatorio[["Posi","pos_ind","Neg","neg_ind","Neutral","neu_ind","indice"]]

In [33]:
rel.describe()

,Posi,pos_ind,Neg,neg_ind,Neutral,neu_ind,indice
count,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000,19.000000
mean,187.315789,0.117165,275.052632,0.170425,1145.368421,0.712409,-0.053260
std,39.392685,0.023559,55.782787,0.020187,146.468886,0.012398,0.042088
min,124.000000,0.070044,219.000000,0.149196,1020.000000,0.687170,-0.127753
25%,158.500000,0.099463,241.000000,0.153745,1064.000000,0.708158,-0.088850
50%,175.000000,0.117845,258.000000,0.164983,1107.000000,0.711237,-0.040900
75%,216.000000,0.138345,288.000000,0.188900,1162.500000,0.720288,-0.017748
max,250.000000,0.153506,449.000000,0.209246,1662.000000,0.733888,0.000000

In [30]:
transcricao.describe()

,Posi,pos_ind,Neg,neg_ind,Neutral,neu_ind,indice
count,562.000000,562.000000,562.000000,562.000000,562.000000,562.000000,562.000000
mean,107.895018,0.282152,48.314947,0.123093,237.766904,0.594755,0.159059
std,55.147296,0.112369,25.220781,0.047052,102.309538,0.098493,0.141352
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.333333
25%,71.250000,0.212492,29.000000,0.092623,172.000000,0.526800,0.080660
50%,103.000000,0.276725,45.000000,0.118889,221.000000,0.598125,0.154700
75%,136.000000,0.353413,64.000000,0.149207,292.750000,0.662633,0.249592
max,371.000000,1.000000,135.000000,0.333333,638.000000,0.872534,1.000000